$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path

$Header = Get-Content -Raw (Join-Path $Root "Source\Music\MotifDevelopment.h")
$Impl = Get-Content -Raw (Join-Path $Root "Source\Music\MotifDevelopment.cpp")
$PlanHeader = Get-Content -Raw (Join-Path $Root "Source\Music\PhraseDevelopmentPlan.h")
$Plan = Get-Content -Raw (Join-Path $Root "Source\Music\PhraseDevelopmentPlan.cpp")
$Composer = Get-Content -Raw (Join-Path $Root "Source\Music\MotifPhraseComposer.cpp")
$Tests = Get-Content -Raw (Join-Path $Root "Source\Tests\MusicalEngineTests.cpp")

if ($Header -notmatch "Motif\s+retrograde\s*\(")
{
    throw "MotifDevelopment::retrograde declaration is missing."
}

if ($Impl -notmatch "MotifDevelopment::retrograde")
{
    throw "MotifDevelopment::retrograde implementation is missing."
}

if ($PlanHeader -notmatch "retrogradeMotif")
{
    throw "PhraseDevelopmentPlan lacks response retrograde semantics."
}

if ($Plan -notmatch "retrogradeMotif")
{
    throw "Response retrograde policy is not generated by PhraseDevelopmentPlan."
}

if ($Plan -notmatch "resolveDevelopmentRole")
{
    throw "Dedicated phrase-role resolver is missing."
}

if ($Plan -notmatch "sectionCount >= 5")
{
    throw "Response role must require a five-section phrase grammar."
}

if ($Composer -notmatch "MotifDevelopment::retrograde")
{
    throw "MotifPhraseComposer does not consume response retrograde development."
}

if ($Tests -notmatch "testMotifResponseDevelopment")
{
    throw "Motif response regression coverage is missing."
}


if ($Plan -notmatch "repetition >= 75")
{
    throw "Restatement priority condition is missing."
}

if ($Tests -notmatch "testPhraseRoleGrammarMatrix")
{
    throw "Phrase-role grammar matrix regression coverage is missing."
}

Write-Host "Phase 18 motif-response validation passed." -ForegroundColor Green
